routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::auth();

Route::get('/', 'HomeController@index')->name('home.index');
Route::get('/register', 'GroupController@index')->name('register');
Route::resource('posts', 'PostController');
Route::resource('users', 'UserController');
Route::resource('groups', 'GroupController');
Route::resource('faq', 'FaqController');

Route::get('/scoreboard', 'ScoreboardController@index')->name('scoreboard');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('tasks', 'TaskController');
    Route::resource('news', 'NewsController');
    Route::resource('courses', 'CourseController');
    Route::resource('universities', 'UniversityController');

    Route::get('/post/like/{id}', ['as' => 'post.like', 'uses' => 'PostController@like']);
    Route::get('/post/new/{id}', ['as' => 'post.new', 'uses' => 'PostController@new']);
    Route::get('/task/new/{id}', ['as' => 'task.new', 'uses' => 'TaskController@new']);

    Route::get('/user/role/{id}', ['as' => 'user.role', 'uses' => 'UserController@role']);
    Route::get("search","UserController@search");

    Route::post('courses/{course}/participate', 'ParticipationController@store')->name('participation.store');
    Route::delete('courses/{course}/participate', 'ParticipationController@destroy')->name('participation.destroy');


    Route::group(['prefix' => 'tasks', 'as' => 'tasks.'], function () {
        Route::post('/{task}/submit', 'TaskController@submit')->name('submit');
    });

Route::group(['prefix' => 'news', 'as' => 'news.'], function () {
    Route::post('/{news}/submit', 'NewsController@submit')->name('submit');
});
});

app/User.php
<?php

namespace App;

use App\Enums\UserRole;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Nicolaslopezj\Searchable\SearchableTrait;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;
    use SearchableTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'role_id',
        'password',
        'group_id'
    ];

    protected $searchable = [
        'columns' => [
            'name' => 15,
            'email' => 10,
        ]
    ];


    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected static function boot()
    {
        parent::boot();
    }

//    public function tasks()
//    {
//        return $this->hasManyThrough(Task::class, Submission::class)->where('submissions.correct', true);
//    }

    public function group()
    {
        return $this->belongsTo(Group::class);
    }


    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    public function submissions()
    {
        return $this->hasMany(Submission::class)->orderBy('submission');
    }

    public function news()
    {
        return $this->hasMany(News::class);
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function courses()
    {
        return $this->hasMany(Course::class);
    }

    public function participations()
    {
        return $this->belongsToMany(Course::class, 'course_user', 'user_id', 'course_id')
            ->as('participation')
            ->withTimestamps();
    }


    public function getIsAdminAttribute()
    {
        return $this->role_id == UserRole::Admin;
    }

    public function getIsTeacherAttribute()
    {
        return $this->role_id == UserRole::Teacher;
    }

    public function getIsContestantAttribute()
    {
        return $this->role_id == UserRole::Contestant;
    }

    /**
     * @return \Illuminate\Support\Collection
     */
    public function getSolvedTasksAttribute()
    {
        return $this->submissions->pluck('task');
    }

    public function getScoreAttribute()
    {
//        return $this->tasks()->sum('cost');
        return $this->solved_tasks->sum('cost');
    }

    public function getScoreForCategory(Category $category)
    {
        return $this->solved_tasks->where('category_id', $category->id)->sum('cost');
    }

    public function scopeContestants(Builder $builder)
    {
        return $builder->where('role_id', UserRole::Contestant);
    }

    public function scopeActive(Builder $builder)
    {
        return $builder->whereHas('submissions', function (Builder $builder) {
            $builder->where('correct', true);
        });
    }
}

resources/views/app/_navbar.blade.php
<nav class="navbar navbar-expand-md navbar-light navbar-laravel">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'CTF') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">
                @auth
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('tasks.index') }}">{{ __('Задания') }}</a>
                    </li>


                    @if(auth()->user()->isTeacher || auth()->user()->isAdmin)
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('courses.create')}}">Cоздать курс</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('users.index')}}">Пользователи</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('universities.index')}}">Университеты</a>
                        </li>
                    @endif
                @endauth



                <li class="nav-item">
                    <a class="nav-link" href="{{ route('scoreboard') }}">{{ __('Scoreboard') }}</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{route('posts.index')}}">Разборы</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{route('courses.index')}}">Курсы</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{route('faq.index')}}">FAQ</a>
                </li>
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    <li class="nav-item">
                        @if (Route::has('register'))
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        @endif
                    </li>
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }}

                            @if(Auth::user()->group)
                                <span class="text-info">{{Auth::user()->group->shipher}}</span>
                            @endif
                            ({{ Auth::user()->score }})<span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Выйти') }}
                            </a>

                    @if(auth()->user()->isAdmin)

                            <a class="dropdown-item" href="{{route('tasks.create')}}">Создать задание</a>



                            <a class="dropdown-item" href="{{route('news.create')}}">Создать новость</a>

                    @endif

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>