routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::auth();

Route::get('/', 'HomeController@index')->name('home.index');
Route::get('/register', 'GroupController@index')->name('register');
Route::resource('posts', 'PostController');
Route::resource('users', 'UserController');
Route::resource('groups', 'GroupController');
Route::resource('faq', 'FaqController');

Route::get('/scoreboard', 'ScoreboardController@index')->name('scoreboard');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('tasks', 'TaskController');
    Route::resource('news', 'NewsController');
    Route::resource('courses', 'CourseController');
    Route::resource('universities', 'UniversityController');

    Route::get('/post/like/{id}', ['as' => 'post.like', 'uses' => 'PostController@like']);
    Route::get('/post/new/{id}', ['as' => 'post.new', 'uses' => 'PostController@new']);
    Route::get('/task/new/{id}', ['as' => 'task.new', 'uses' => 'TaskController@new']);

    Route::get('/user/role/{id}', ['as' => 'user.role', 'uses' => 'UserController@role']);
    Route::get("search","UserController@search");

    Route::post('courses/{course}/participate', 'ParticipationController@store')->name('participation.store');
    Route::delete('courses/{course}/participate', 'ParticipationController@destroy')->name('participation.destroy');


    Route::group(['prefix' => 'tasks', 'as' => 'tasks.'], function () {
        Route::post('/{task}/submit', 'TaskController@submit')->name('submit');
    });

Route::group(['prefix' => 'news', 'as' => 'news.'], function () {
    Route::post('/{news}/submit', 'NewsController@submit')->name('submit');
});
});

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\News;
use App\Group;
use Illuminate\Database\Eloquent\Builder;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = auth()->user();

        $categories = \App\Category::whereHas('tasks')
            ->whereHas('tasks.submissions', function (Builder $builder) use ($user) {
                return $builder->byUser($user);
            })
            ->with([
                'tasks:cost',
                'tasks.submissions:correct',
            ])
            ->get();

        $submissions = $user->submissions()
            ->withoutGlobalScope('correctOnly')
            ->with(['task'])
            ->get();

        $news=News::all()->sortByDesc('updated_at');
        return view('home.index', compact('categories', 'user', 'submissions','news'));
    }
}

resources/views/home/index.blade.php
@extends('layouts._app')

@section('content')
    <div class="container">
        <div class="row">

            <div class="col col-12 col-md-4">
                @include('home.cards.category_breakdown')

                @include('home.cards.submission_percentage')
            </div>

            <div class="col col-12 col-md-8">
                <div class="card mb-3">
                    <div class="card-header">News</div>
                    @foreach($news as $new)
                    <div class="card-body">
                         <h4>{{$new->title}}</h4>
                        <div class="row">
                            <div class="col-md-3">
                                {{$new->updated_at->diffForHumans()}}
                            </div>
                             <div class="col-md-6">{{$new->user->name}}</div>
                        </div>
                            <p>{{$new->body}}</p>
                        <div class="row">
                            <div class="col-md-6">
                                @can('update', $new)
                                    <a href="{{route('news.edit',$new)}}" class="btn btn-block btn-primary">Edit</a>
                                @endcan
                            </div>

                            <div class="col-md-6">
                                @can('delete', $new)
                                    <form method="POST" action="{{route('news.destroy', $new)}}">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-block btn-danger" type="submit">Delete</button>
                                    </form>
                                @endcan
                            </div>
                        </div>
                    </div>
                    @endforeach
                </div>
            </div>
        </div>
        @if($user->solved_tasks->count() > 0)
            <div class="row mt-3">
                <div class="col col-12">
                    <h3>Solves ({{ $user->solved_tasks->count() }})</h3>
                </div>
                <div class="col col-12">
                    <div class="card-columns">
                        @foreach($user->solved_tasks as $task)
                            @include('tasks._card')
                        @endforeach
                    </div>
                </div>
            </div>
        @endif

        @if($user->courses->count() > 0)
            <div class="row mt-3">
                <div class="col col-12">
                    <h3>Мои Курсы ({{ $user->courses->count() }})</h3>
                </div>
                <div class="col col-12">

                    @foreach($user->courses as $course)
                        <a href="{{ route('courses.show', $course) }}" class="list-group-item list-group-item-action">
                            @include('courses._card')
                        </a>
                    @endforeach
                </div>
            </div>
        @endif

        @if($user->participations->count() > 0)
            <div class="row mt-3">
                <div class="col col-12">
                    <h3>Курсы на которые я записан ({{ $user->participations->count() }})</h3>
                </div>
                <div class="col col-12">

                        @foreach($user->participations as $course)
                        <a href="{{ route('courses.show', $course) }}" class="list-group-item list-group-item-action">
                            @include('courses._card')
                        </a>
                        @endforeach
                </div>
            </div>
        @endif
    </div>
@endsection