routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::auth();

Route::get('/', 'HomeController@index')->name('home.index');
Route::get('/register', 'GroupController@index')->name('register');
Route::resource('posts', 'PostController');
Route::resource('users', 'UserController');
Route::resource('groups', 'GroupController');
Route::resource('faq', 'FaqController');

Route::get('/scoreboard', 'ScoreboardController@index')->name('scoreboard');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('tasks', 'TaskController');
    Route::resource('news', 'NewsController');
    Route::resource('courses', 'CourseController');
    Route::resource('universities', 'UniversityController');

    Route::get('/post/like/{id}', ['as' => 'post.like', 'uses' => 'PostController@like']);
    Route::get('/post/new/{id}', ['as' => 'post.new', 'uses' => 'PostController@new']);
    Route::get('/task/new/{id}', ['as' => 'task.new', 'uses' => 'TaskController@new']);

    Route::get('/user/role/{id}', ['as' => 'user.role', 'uses' => 'UserController@role']);
    Route::get("search","UserController@search");

    Route::post('courses/{course}/participate', 'ParticipationController@store')->name('participation.store');
    Route::delete('courses/{course}/participate', 'ParticipationController@destroy')->name('participation.destroy');


    Route::group(['prefix' => 'tasks', 'as' => 'tasks.'], function () {
        Route::post('/{task}/submit', 'TaskController@submit')->name('submit');
    });

Route::group(['prefix' => 'news', 'as' => 'news.'], function () {
    Route::post('/{news}/submit', 'NewsController@submit')->name('submit');
});
});

app/Task.php
<?php

namespace App;

use App\Enums\TaskStatus;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $fillable = [
        'title',
        'lead',
        'description',
        'cost',
        'correct_answer',
        'category_id',
        'course_id',
        'status',
        'blocked_by_ids',
    ];

    protected $casts = [
        'cost' => 'integer',
        'blocked_by_ids' => 'array',
    ];

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('visibleOnly', function (Builder $builder) {
            return $builder->where('status', TaskStatus::Open)
                ->orWhere('status', TaskStatus::Blocked);
        });

        static::addGlobalScope('sortByCost', function (Builder $builder) {
            return $builder->orderBy('cost');
        });
    }

    public function isSolvedBy(User $user = null)
    {
        if (is_null($user)) {
            $user = auth()->user();
        }

        return $this->submissions->where('user_id', $user->id)->count() > 0;
    }

    public function users()
    {
        return $this->hasManyThrough(User::class, Submission::class);
    }

    public function submissions()
    {
        return $this->hasMany(Submission::class);
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class)->withDefault([
            'id' => -1,
            'title' => 'Uncategorized',
        ]);
    }

    public function course()
    {
        return $this->belongsTo(Course::class);
    }

    public function getIsSolvedAttribute()
    {
        return $this->isSolvedBy(auth()->user());
    }

    public function getSolvedByAttribute()
    {
        return $this->submissions->pluck('user');
    }

    public function getIsBlockedAttribute()
    {
        return $this->status == TaskStatus::Blocked
            && (!$this->blocked_by->every(function (Task $task) {
                    return $task->isSolvedBy(auth()->user());
            })
                || $this->blocked_by->isEmpty());
    }

    /**
     * @return Task[]|\Illuminate\Database\Eloquent\Collection|\Illuminate\Support\Collection
     */
    public function getBlockedByAttribute()
    {
        if (empty($this->blocked_by_ids)) {
            return collect();
        } else {
            return Task::whereIn('id', $this->blocked_by_ids)->get();
        }
    }
}

app/User.php
<?php

namespace App;

use App\Enums\UserRole;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Nicolaslopezj\Searchable\SearchableTrait;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;
    use SearchableTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'role_id',
        'password',
        'group_id'
    ];

    protected $searchable = [
        'columns' => [
            'name' => 15,
            'email' => 10,
        ]
    ];


    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected static function boot()
    {
        parent::boot();
    }

//    public function tasks()
//    {
//        return $this->hasManyThrough(Task::class, Submission::class)->where('submissions.correct', true);
//    }

    public function group()
    {
        return $this->belongsTo(Group::class);
    }


    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    public function submissions()
    {
        return $this->hasMany(Submission::class)->orderBy('submission');
    }

    public function news()
    {
        return $this->hasMany(News::class);
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function courses()
    {
        return $this->hasMany(Course::class);
    }

    public function participations()
    {
        return $this->belongsToMany(Course::class, 'course_user', 'user_id', 'course_id')
            ->as('participation')
            ->withTimestamps();
    }


    public function getIsAdminAttribute()
    {
        return $this->role_id == UserRole::Admin;
    }

    public function getIsTeacherAttribute()
    {
        return $this->role_id == UserRole::Teacher;
    }

    public function getIsContestantAttribute()
    {
        return $this->role_id == UserRole::Contestant;
    }

    /**
     * @return \Illuminate\Support\Collection
     */
    public function getSolvedTasksAttribute()
    {
        return $this->submissions->pluck('task');
    }

    public function getScoreAttribute()
    {
//        return $this->tasks()->sum('cost');
        return $this->solved_tasks->sum('cost');
    }

    public function getScoreForCategory(Category $category)
    {
        return $this->solved_tasks->where('category_id', $category->id)->sum('cost');
    }

    public function scopeContestants(Builder $builder)
    {
        return $builder->where('role_id', UserRole::Contestant);
    }

    public function scopeActive(Builder $builder)
    {
        return $builder->whereHas('submissions', function (Builder $builder) {
            $builder->where('correct', true);
        });
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Enums\TaskType;
use App\Http\Middleware\TeacherOrAdminMiddleware;
use App\Http\Requests\TaskSubmissionRequest;
use App\Http\Requests\Task\TaskStoreRequest;
use App\Http\Requests\TasksUpdateRequest;
use App\Task;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;

class TaskController extends Controller
{

    public function __construct()
    {
        $this->middleware(TeacherOrAdminMiddleware::class, ['except' => ['index', 'show', 'submit']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::orderBy('title')->get();
        $tasks = Task::orderBy('cost')->get();
        return view('tasks.index', compact('tasks', 'categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
            $categories = Category::all();
            return view('tasks.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(TaskStoreRequest $request)
    {
        if (auth()->user()->isAdmin || auth()->user()->isTeacher) {
            $task = Task::create($request->validated());

            return redirect(route('tasks.show', compact('task')));
        } else throw new AuthorizationException('You are not allowed');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Task $task
     * @return \Illuminate\Http\Response
     */
    public function show(Task $task)
    {
        $user = auth()->user();

        $submission = $task->submissions()
            ->byUser($user)
            ->when($task->type == TaskType::Manual, function (Builder $builder) {
                return $builder->withoutGlobalScope('correctOnly');
            })
            ->latest()->first();

        return view('tasks.show', compact('task', 'submission', 'user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Task $task
     * @return \Illuminate\Http\Response
     */
    public function edit(Task $task)
    {
        if (auth()->user()->isAdmin || auth()->user()->isTeacher) {

            $categories = Category::all();
            return view('tasks.edit', compact('task', 'categories'));

        } else throw new AuthorizationException('You are not allowed');

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Task $task
     * @return \Illuminate\Http\Response
     */
    public function update(TasksUpdateRequest $request, Task $task)
    {

        if (auth()->user()->isAdmin || auth()->user()->isTeacher) {
            $user = auth()->user();
            $task->update($request->validated());
            return view('tasks.show', compact('task', 'user'));

        } else throw new AuthorizationException('You are not allowed');


    }

    public function submit(TaskSubmissionRequest $request, Task $task)
    {
        $validated = $request->validated();

        $submission = $validated['submission'];
        $correct = ($task->type == TaskType::Default && $submission == $task->correct_answer);
        $task->submissions()->create([
            'user_id' => auth()->id(),
            'submission' => $submission,
            'correct' => $correct,
        ]);

        $task->syncChanges();

        if(!$submission == $task->correct_answer){
            return redirect()->back()->with('message', 'danger');
        } else {
            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Task $task
     * @return \Illuminate\Http\Response
     */
    public function destroy(Task $task)
    {
        if (auth()->user()->isAdmin || auth()->user()->isTeacher) {

            $task->delete();
            return redirect(route('tasks.index'));

        } else throw new AuthorizationException('You are not allowed');
    }

    public function new($id)
    {
        if (auth()->user()->isAdmin || auth()->user()->isTeacher) {

            $categories = Category::all();
            return view('tasks.create', compact('id', 'categories'));

        } else throw new AuthorizationException('You are not allowed');
    }
}

resources/views/tasks/_card.blade.php
<div id="task-{{ $task->id }}" class="card @if($task->is_solved) border-success @endif">
    <h6 class="card-header">
        {{ $task->title }}<span class="text-muted">&nbsp;&mdash;&nbsp;{{ $task->cost }} {{$task->is_solved}}</span>
    </h6>

    <div class="card-body" >
        @markdown($task->lead)
    </div>

    <div class="card-footer text-muted">
        <div class="btn-group btn-group-justified w-100" role="group" aria-label="Basic example">
            @can('view', $task)
                <a href="{{ route('tasks.show', $task) }}"
                   class="btn btn-sm btn-block @if($task->is_solved) btn-outline-success @else btn-primary @endif"> @if($task->is_solved) Выполнено @else Перейти @endif </a>
            @else
                <button role="button"
                        class="btn btn-sm btn-block btn-outline-primary"
                        data-toggle="popover" data-html="true"
                        title="Task is Blocked"
                        @if($task->blocked_by->isEmpty())
                            data-content="This task is blocked by <b>Administration</b>">
                        @else
                            data-content="This task is blocked by: <ul>{{
                                $task->blocked_by->map(function(\App\Task $task) {
                                    return '<li>' . ($task->is_solved ? '<s>' : '') . '<a href="' . route('tasks.show', $task) . '">' . $task->title . '</a>' . ($task->is_solved ? '</s>' : '') . '</li>';
                                })->implode('')
                            }}</ul>">
                        @endif
                    Заблокированно
                </button>
            @endcan

        </div>
    </div>
</div>

resources/views/tasks/_form.blade.php
<div class="row">
    <div class="col-md-8 mt-2">
        <div class="card">
            <div class="card-body">
                <div class="form-group">
                    {{ Form::label('title', 'Заголовок задания') }}
                    {{ Form::text('title', null, ['class' => 'form-control']) }}
                    @if($errors->has('title'))
                        <div class="invalid-feedback">{{$errors->first('title')}}</div>
                    @endif
                </div>

                <div class="form-group">
                    {{ Form::label('lead', 'Аннотация задания') }}
                    {{ Form::textarea('lead', null, ['class' => 'form-control', 'rows' => 5]) }}
                    @if(@isset($id))
                        {{ Form::hidden('course_id', $id, ['class' => 'form-control']) }}
                    @else
                        {{ Form::hidden('course_id', null, ['class' => 'form-control']) }}
                    @endif
                </div>
                <div class="form-group">
                    {{ Form::label('description', 'Описание задания') }}
                    {{ Form::textarea('description', null, ['class' => 'form-control', 'rows' => 10]) }}
                    @if($errors->has('description'))
                        <div class="invalid-feedback">{{$errors->first('description')}}</div>
                    @endif
                </div>

            </div>
        </div>
    </div>

    <div class="col-md-4 mt-2">
        <div class="card">
            <div class="card-header">Info</div>
            <div class="card-body">
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            {{ Form::label('correct_answer', 'Answer') }}
                            {{ Form::text('correct_answer', null, ['class' => 'form-control']) }}
                        </div>
                        <div class="form-group">
                            {{ Form::label('cost', 'cost') }}
                            {{ Form::number('cost', null, ['class' => 'form-control']) }}
                            @if($errors->has(''))
                                <div class="invalid-feedback">{{$errors->first('cost')}}</div>
                            @endif
                        </div>
                        <div class="form-group">
                            {{ Form::label('category_id', 'category_id') }}
                            {{ Form::select('category_id', $categories->pluck('title', 'id')->all() , null, ['class' => 'form-control'], ['placeholder' => 'Pick a category...'])}}

                        </div>
                        <div class="form-group">
                            {{ Form::label('status', 'status') }}
                            {{ Form::select('status', ['open' => 'open', 'blocked' => 'blocked'], null, ['class' => 'form-control'], ['placeholder' => 'Pick a status...'])}}
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                {{  Form::submit('Сохранить', ['class' => 'btn btn-primary btn-block']) }}
            </div>
        </div>
    </div>
</div>

resources/views/tasks/create.blade.php
@extends('layouts._app')

@section('content')
    <div class="container">
        {{ Form::open(['role' => 'form', 'id' => 'tasks-form', 'route' => 'tasks.store', 'method' => 'post']) }}
        @include('tasks._form')
        {{ Form::close() }}
    </div>
@endsection

resources/views/tasks/edit.blade.php
@extends('layouts._app')

@section('content')
    <div class="container">
        {{ Form::model($task,['role' => 'form', 'id' => 'tasks-form', 'route' => ['tasks.update',$task->id], 'method' => 'put']) }}
        @include('tasks._form')
        {{ Form::close() }}
    </div>
@endsection

resources/views/tasks/index.blade.php
@extends('layouts._app')

@section('content')
    <div class="container">
        <div class="row">
            @foreach($categories as $category)
                <div class="col col-12 mb-4">
                    <h3>{{ $category->title }}</h3>

                    <div class="card-columns">
                        @foreach($category->tasks as $task)
                            @include('tasks._card')
                        @endforeach
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endsection

resources/views/tasks/show.blade.php
@extends('layouts._app')

@section('content')
    <div class="container">

        <div class="row">
            <div class="col col-12 ">
                <div class="card mb-3">
                    <div class="card-header">
                        <div class="d-flex align-items-center">
                            <h5 class="mr-auto">{{$task->title}}<span class="text-muted">&nbsp;&mdash;&nbsp;{{ $task->cost }}</span></h5>
                            <div class="row justify-content-center">
                                <div class="col-4">
                                    @can('update', $task)
                                        <a href="{{route('tasks.edit',$task)}}" class="btn btn-outline-primary">Edit</a>
                                    @endcan
                                </div>
                                <div class="col-5">
                                    @can('delete', $task)
                                        <form method="POST" action="{{route('tasks.destroy', $task)}}">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-outline-danger" type="submit">Delete</button>
                                        </form>
                                    @endcan
                                </div>

                            </div>
                        </div>
                    </div>

                    <div class="card-body">
                        @if($task->course_id)
                            @include('tasks.alerts.course')
                        @endif
                        @if($task->is_solved)
                            @include('tasks.alerts.solved')
                        @endif

                        @if($task->is_blocked)
                            @include('tasks.alerts.blocked')
                        @endif
                        @markdown($task->description)
                        {{$task->correct_answer}}
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col col-12 ">
                <div class="card mb-3">
                    <div class="card-header">
                        <div class="d-flex align-items-center">
                            <h5 class="mr-auto ">Разборы задания <span class="text-muted">&nbsp;&mdash;&nbsp;{{ $task->posts()->count() }}</span></h5>
                            <div>
                                <a class="btn btn-outline-primary" href="{{route('post.new', $task->id)}}">Создать свой пост</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">

                        <div class="card-columns">

                            @foreach($task->posts as $post)
                                @include('posts._card')
                            @endforeach
                        </div>

                    </div>
                </div>
            </div>
        </div>
        @can('edit', $task)
        <div class="row">
            <div class="col col-12 ">
                <div class="card mb-3">
                    <div class="card-header">
                        <div class="d-flex align-items-center">
                            <h5 class="mr-auto ">Правильных ответов <span class="text-muted">&nbsp;&mdash;&nbsp;{{ $task->solved_by->count() }}</span></h5>
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="table table-hover text-decoration-none">
                            <tr>
                                <th>Имя пользователя</th>
                                <th>Попытки решения</th>
                                <th>Количество очков</th>
                            </tr>
                            @foreach($task->solved_by as $user)
                                <tr>
                                    <td>{{$user->name}}</td>
                                    <td>{{$task->submissions()->byUser($user)->withoutGlobalScope('correctOnly')->count()}}</td>
                                    <td>{{$user->score}}</td>
                                </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
            </div>
        </div>
        @endcan

        @includeIf('tasks.submission.default')
    </div>
@endsection