routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::auth();

Route::get('/', 'HomeController@index')->name('home.index');
Route::get('/register', 'GroupController@index')->name('register');
Route::resource('posts', 'PostController');
Route::resource('users', 'UserController');
Route::resource('groups', 'GroupController');
Route::resource('faq', 'FaqController');

Route::get('/scoreboard', 'ScoreboardController@index')->name('scoreboard');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('tasks', 'TaskController');
    Route::resource('news', 'NewsController');
    Route::resource('courses', 'CourseController');
    Route::resource('universities', 'UniversityController');

    Route::get('/post/like/{id}', ['as' => 'post.like', 'uses' => 'PostController@like']);
    Route::get('/post/new/{id}', ['as' => 'post.new', 'uses' => 'PostController@new']);
    Route::get('/task/new/{id}', ['as' => 'task.new', 'uses' => 'TaskController@new']);

    Route::get('/user/role/{id}', ['as' => 'user.role', 'uses' => 'UserController@role']);
    Route::get("search","UserController@search");

    Route::post('courses/{course}/participate', 'ParticipationController@store')->name('participation.store');
    Route::delete('courses/{course}/participate', 'ParticipationController@destroy')->name('participation.destroy');


    Route::group(['prefix' => 'tasks', 'as' => 'tasks.'], function () {
        Route::post('/{task}/submit', 'TaskController@submit')->name('submit');
    });

Route::group(['prefix' => 'news', 'as' => 'news.'], function () {
    Route::post('/{news}/submit', 'NewsController@submit')->name('submit');
});
});

app/Submission.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Submission extends Model
{
    protected $fillable = [
        'task_id',
        'user_id',
        'submission',
        'correct'
    ];

    protected $casts = [
        'correct' => 'boolean',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
    ];

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('correctOnly', function (Builder $builder) {
            return $builder->where('correct', true);
        });
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function task()
    {
        return $this->belongsTo(Task::class);
    }

    public function getIsReviewedAttribute()
    {
        return $this->created_at != $this->updated_at;
    }

    public function scopeByUser(Builder $builder, User $user)
    {
        return $builder->where('user_id', $user->id);
    }
}

app/Task.php
<?php

namespace App;

use App\Enums\TaskStatus;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $fillable = [
        'title',
        'lead',
        'description',
        'cost',
        'correct_answer',
        'category_id',
        'course_id',
        'status',
        'blocked_by_ids',
    ];

    protected $casts = [
        'cost' => 'integer',
        'blocked_by_ids' => 'array',
    ];

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('visibleOnly', function (Builder $builder) {
            return $builder->where('status', TaskStatus::Open)
                ->orWhere('status', TaskStatus::Blocked);
        });

        static::addGlobalScope('sortByCost', function (Builder $builder) {
            return $builder->orderBy('cost');
        });
    }

    public function isSolvedBy(User $user = null)
    {
        if (is_null($user)) {
            $user = auth()->user();
        }

        return $this->submissions->where('user_id', $user->id)->count() > 0;
    }

    public function users()
    {
        return $this->hasManyThrough(User::class, Submission::class);
    }

    public function submissions()
    {
        return $this->hasMany(Submission::class);
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class)->withDefault([
            'id' => -1,
            'title' => 'Uncategorized',
        ]);
    }

    public function course()
    {
        return $this->belongsTo(Course::class);
    }

    public function getIsSolvedAttribute()
    {
        return $this->isSolvedBy(auth()->user());
    }

    public function getSolvedByAttribute()
    {
        return $this->submissions->pluck('user');
    }

    public function getIsBlockedAttribute()
    {
        return $this->status == TaskStatus::Blocked
            && (!$this->blocked_by->every(function (Task $task) {
                    return $task->isSolvedBy(auth()->user());
            })
                || $this->blocked_by->isEmpty());
    }

    /**
     * @return Task[]|\Illuminate\Database\Eloquent\Collection|\Illuminate\Support\Collection
     */
    public function getBlockedByAttribute()
    {
        if (empty($this->blocked_by_ids)) {
            return collect();
        } else {
            return Task::whereIn('id', $this->blocked_by_ids)->get();
        }
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Enums\TaskType;
use App\Http\Middleware\TeacherOrAdminMiddleware;
use App\Http\Requests\TaskSubmissionRequest;
use App\Http\Requests\Task\TaskStoreRequest;
use App\Http\Requests\TasksUpdateRequest;
use App\Task;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;

class TaskController extends Controller
{

    public function __construct()
    {
        $this->middleware(TeacherOrAdminMiddleware::class, ['except' => ['index', 'show', 'submit']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::orderBy('title')->get();
        $tasks = Task::orderBy('cost')->get();
        return view('tasks.index', compact('tasks', 'categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
            $categories = Category::all();
            return view('tasks.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(TaskStoreRequest $request)
    {
        if (auth()->user()->isAdmin || auth()->user()->isTeacher) {
            $task = Task::create($request->validated());

            return redirect(route('tasks.show', compact('task')));
        } else throw new AuthorizationException('You are not allowed');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Task $task
     * @return \Illuminate\Http\Response
     */
    public function show(Task $task)
    {
        $user = auth()->user();

        $submission = $task->submissions()
            ->byUser($user)
            ->when($task->type == TaskType::Manual, function (Builder $builder) {
                return $builder->withoutGlobalScope('correctOnly');
            })
            ->latest()->first();

        return view('tasks.show', compact('task', 'submission', 'user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Task $task
     * @return \Illuminate\Http\Response
     */
    public function edit(Task $task)
    {
        if (auth()->user()->isAdmin || auth()->user()->isTeacher) {

            $categories = Category::all();
            return view('tasks.edit', compact('task', 'categories'));

        } else throw new AuthorizationException('You are not allowed');

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Task $task
     * @return \Illuminate\Http\Response
     */
    public function update(TasksUpdateRequest $request, Task $task)
    {

        if (auth()->user()->isAdmin || auth()->user()->isTeacher) {
            $user = auth()->user();
            $task->update($request->validated());
            return view('tasks.show', compact('task', 'user'));

        } else throw new AuthorizationException('You are not allowed');


    }

    public function submit(TaskSubmissionRequest $request, Task $task)
    {
        $validated = $request->validated();

        $submission = $validated['submission'];
        $correct = ($task->type == TaskType::Default && $submission == $task->correct_answer);
        $task->submissions()->create([
            'user_id' => auth()->id(),
            'submission' => $submission,
            'correct' => $correct,
        ]);

        $task->syncChanges();

        if(!$submission == $task->correct_answer){
            return redirect()->back()->with('message', 'danger');
        } else {
            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Task $task
     * @return \Illuminate\Http\Response
     */
    public function destroy(Task $task)
    {
        if (auth()->user()->isAdmin || auth()->user()->isTeacher) {

            $task->delete();
            return redirect(route('tasks.index'));

        } else throw new AuthorizationException('You are not allowed');
    }

    public function new($id)
    {
        if (auth()->user()->isAdmin || auth()->user()->isTeacher) {

            $categories = Category::all();
            return view('tasks.create', compact('id', 'categories'));

        } else throw new AuthorizationException('You are not allowed');
    }
}

resources/views/tasks/submission/default.blade.php
@can('submit', $task)
    <div class="row">
        <div class="col col-12 ">
            <div class="card">
                <div class="card-header">
                    <ul class="nav nav-tabs card-header-tabs">
                        <li class="nav-item">
                            <a class="nav-link active" id="submit-tab" data-toggle="tab" href="#submit"
                               role="tab"
                               aria-controls="home" aria-selected="true">Submit</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="previous-tab" data-toggle="tab" href="#previous" role="tab"
                               aria-controls="home" aria-selected="false">Previous</a>
                        </li>
                    </ul>
                </div>

                <div class="card-body">
                    <div class="tab-content">

                        <div class="tab-pane active" id="submit" role="tabpanel" aria-labelledby="submit-tab">
                            <form method="POST" action="{{ route('tasks.submit', $task) }}">
                                @csrf

                                <div class="form-group row">
                                    <div class="col col-12">
                                    @if(session()->has('message'))
                                        <div class="alert alert-{{ session()->get('message') }}">

                                            Your answer is incorrect

                                        </div>
                                    @endif
                                        <label for="submission">Your answer:</label>
                                        <textarea rows="3" class="form-control"
                                                  id="submission" name="submission"
                                                  @if($task->is_solved) disabled @endif>{{ old('submission') }}</textarea>
                                    </div>
                                </div>

                                <button type="submit" class="btn btn-primary "
                                        @if($task->is_solved) disabled @endif>Submit
                                </button>
                            </form>
                        </div>

                        <div class="tab-pane" id="previous" role="tabpanel" aria-labelledby="previous-tab">
                            <table class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th scope="col">Submission</th>
                                    <th scope="col">Time</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($task->submissions()->byUser($user)->withoutGlobalScope('correctOnly')->get() as $submission)
                                    <tr class="@if($submission->correct) table-success @endif">
                                        <td><code>{{ $submission->submission }}</code></td>
                                        <td>{{ $submission->created_at }}</td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endcan

resources/views/tasks/submission/manual.blade.php
<div class="row">
    <div class="col col-12 ">
        <div class="card">
            <div class="card-header">
                Submit
            </div>

            <div class="card-body">
                @if(empty($submission) || (!$submission->correct && $submission->is_reviewed))
                    @if(optional($submission)->is_reviewed)
                        <div class="alert alert-danger" role="alert">
                            Your submission has been rejected!
                        </div>
                    @endif

                    <form method="POST" action="{{ route('tasks.submit', $task) }}">
                        @csrf

                        <div class="form-group row">
                            <div class="col col-12">
                                <textarea id="submission" class="form-control" name="submission"></textarea>
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary "
                                @if($task->is_solved) disabled @endif>Submit
                        </button>
                    </form>
                @else
                    @if($submission->correct)
                        <div class="alert alert-success" role="alert">
                            Your submission has been reviewed and accepted!
                        </div>
                    @elseif($submission->is_reviewed)
                        <div class="alert alert-danger" role="alert">
                            Your submission has been rejected!
                        </div>
                    @else
                        <div class="alert alert-info" role="alert">
                            Your submission is being reviewed
                        </div>
                    @endif

                    @markdown($submission->submission)
                @endif
            </div>
        </div>
    </div>
</div>

@push('html-body-bottom')
    <script>
        window.addEventListener('DOMContentLoaded', function () {
            var simplemde = new SimpleMDE({
                element: document.getElementById("submission"),
                autofocus: true,
                autosave: {
                    enabled: true,
                    uniqueId: "task-{{ $task->id }}",
                    delay: 1000,
                },
                forceSync: true,
                placeholder: "Type here...",
                showIcons: ["code", "table"],
                spellChecker: false,
            });
        })
    </script>
@endpush